# Backend server configuration
backend:
  # Port on which to serve the API
  port: 8081
  # BadgerDB directory for radio samples
  storage: /samples
  # List of users as 'username: password' pairs for basic auth on the HTTP API endpoints
  users:
    openrfsense: openrfsense

# Collector service configuration
collector:
  # Port on which to wait for TCP packets
  port: 2022

# PostgreSQL database configuration
postgres:
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  dbname: postgres
  # Extra connection parameters, see PostgreSQL documentation
  params:
    - sslmode=disable

# NATS server configuration
nats:
  # Port for the NATS server
  port: 4222