# Backend server configuration
backend:
  # Port on which to serve the API
  port: 8081
  # List of users as 'username: password' pairs for basic auth on the HTTP API endpoints
  users:
    openrfsense: openrfsense

# NATS server configuration
nats:
  # Port for the NATS server
  port: 4222