basePath: /api/v1
definitions:
  models.Campaign:
    properties:
      begin:
        description: The time at which the campaign is supposed to start
        type: string
      campaignId:
        description: The textual, random ID for the campaign
        type: string
      createdAt:
        type: string
      end:
        description: The time at which the campaign will end
        type: string
      sensors:
        description: The list of sensor partaking in the campaign
        items:
          type: string
        type: array
      type:
        description: The type of measurements requested
        type: string
    type: object
  models.Sample:
    properties:
      campaignId:
        description: Unique identifier for the campaign this sample belongs to
        type: string
      config:
        $ref: '#/definitions/models.SampleConfig'
        description: Sensor configuration for the recorded data set
      createdAt:
        type: string
      data:
        description: Actual measurement data. Unit depends on measurement type
        items:
          type: number
        type: array
      sampleType:
        description: Sample type string (IQ, PSD, DEC)
        type: string
      sensorId:
        description: The unique hardware id of the sensor
        type: string
      time:
        $ref: '#/definitions/models.SampleTime'
        description: Sample timestamp with microseconds precision
    type: object
  models.SampleConfig:
    properties:
      antennaGain:
        description: Antenna gain in dBi
        type: number
      antennaId:
        description: Identifier for the antenna being used if device has multiple
          antennas
        type: integer
      centerFreq:
        description: Center frequency in Hz to which the RF front-end was tuned to
          while recording the associated spectrum data
        type: integer
      estNoiseFloor:
        description: Estimated noise floor in dB
        type: number
      extraConf:
        additionalProperties: true
        description: Extra configuration for arbitrary data
        type: object
      frequencyCorrectionFactor:
        description: Correction factor for center frequency in Hz. The correction
          is already applied to the center frequency (0.0 for no correction)
        type: number
      frontendGain:
        description: RF front-end gain in dB (-1 for automatic gain control)
        type: number
      hoppingStrategy:
        description: Hopping strategy  used to overcome the bandwidth limitations
          of the RF front-end (0:Sequential, 1:Random, 2:Similarity)
        type: integer
      iqBalanceCalibration:
        description: True if IQ samples are balanced
        type: boolean
      rfSync:
        description: 'Time synchronization of the radio frontend (0: none, 1: GPS,
          2: Reference Clock, 5: Other)'
        type: integer
      samplingRate:
        description: Sensor's sampling rate in samples per second
        type: integer
      sigStrengthCalibration:
        description: True if signal strength is calibrated
        type: boolean
      systemSync:
        description: 'Time synchronization of the system (0: none, 1: GPS, 2: Reference
          Clock, 3: NTP, 4: OpenSky, 5: Other)'
        type: string
    type: object
  models.SampleTime:
    properties:
      microseconds:
        description: Microseconds extension for the UNIX time stamp
        type: integer
      seconds:
        description: Number of seconds since the UNIX epoch start on January 1st,
          1970 at UTC
        type: integer
    type: object
  stats.Stats:
    properties:
      hostname:
        description: Hostname of the system
        type: string
      id:
        description: A unique identifier for the node (a hardware-bound ID is recommended)
        type: string
      model:
        description: The model/vendor of the system's hardware, useful for identification
        type: string
      providers:
        additionalProperties: true
        description: Extra, more in-depth information about the system as dynamically
          returned by providers.
        type: object
      uptime:
        description: Uptime of the system
        type: integer
    type: object
  types.AggregatedMeasurementRequest:
    properties:
      begin:
        description: Start time in ISO 8601
        type: string
      campaignId:
        description: Campaign ID. For internal use only, will be ignored if not null
        type: string
      end:
        description: End time in ISO 8601
        type: string
      freqMax:
        description: Upper bound for frequency in Hz
        type: integer
      freqMin:
        description: Lower bound for frequency in Hz
        type: integer
      freqRes:
        description: Frequency resolution in Hz
        type: integer
      sensors:
        description: List of sensor hardware IDs to run the measurement campaign on
        items:
          type: string
        type: array
      timeRes:
        description: Time resolution in seconds
        type: integer
    type: object
  types.RawMeasurementRequest:
    properties:
      begin:
        description: Start time in ISO 8601
        type: string
      campaignId:
        description: Campaign ID. For internal use only, will be ignored if not null
        type: string
      end:
        description: End time in ISO 8601
        type: string
      freqCenter:
        description: Center frequency for measurement
        type: integer
      sensors:
        description: List of sensor hardware IDs to run the measurement campaign on
        items:
          type: string
        type: array
    type: object
info:
  contact:
    name: OpenRFSense
    url: https://github.com/openrfsense/backend/issues
  description: OpenRFSense backend API
  license:
    name: AGPLv3
    url: https://spdx.org/licenses/AGPL-3.0-or-later.html
  title: OpenRFSense backend API
paths:
  /aggregated:
    post:
      consumes:
      - application/json
      description: Sends an aggregated measurement request to the nodes specified
        in `sensors` and returns a list of `stats.Stats` objects for all sensors taking
        part in the campaign. Will time out in `300ms` if any sensor does not respond.
      parameters:
      - description: Measurement request object
        in: body
        name: id
        required: true
        schema:
          $ref: '#/definitions/types.AggregatedMeasurementRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Bare statistics for all nodes in the measurement campaign.
            Will always include sensor status information.
          headers:
            Location:
              description: Location of the new campaign object.
              type: string
          schema:
            items:
              $ref: '#/definitions/stats.Stats'
            type: array
        "500":
          description: When the internal timeout for information retrieval expires
      security:
      - BasicAuth: []
      summary: Get an aggregated spectrum measurement from a list of nodes
      tags:
      - measurement
  /campaigns:
    get:
      description: Returns a list of campaigns that were successfully started. Will
        return all campaigns unless either of the query parameters is set.
      parameters:
      - description: Matches campigns which contain ALL these sensors as a comma-separated
          list.
        in: path
        name: sensors
        type: string
      - description: Matches a single campaign by its unique ID.
        in: path
        name: campaignId
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: All recorded campaigns which match the given parameters
          schema:
            items:
              $ref: '#/definitions/models.Campaign'
            type: array
        "500":
          description: Generally a database error
      security:
      - BasicAuth: []
      summary: List campaigns
      tags:
      - data
  /nodes:
    get:
      description: Returns a list of all connected nodes by their hardware ID. Will
        time out in `300ms` if any one of the nodes does not respond.
      produces:
      - application/json
      responses:
        "200":
          description: Bare statistics for all the running and connected nodes
          schema:
            items:
              $ref: '#/definitions/stats.Stats'
            type: array
        "500":
          description: When the internal timeout for information retrieval expires
      security:
      - BasicAuth: []
      summary: List nodes
      tags:
      - administration
  /nodes/{sensor_id}:
    get:
      description: Returns full stats from the node with given hardware ID. Will time
        out in `300ms` if the node does not respond.
      parameters:
      - description: Node hardware ID
        in: path
        name: sensor_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Full system statistics for the node associated to the given
            ID
          schema:
            $ref: '#/definitions/stats.Stats'
        "500":
          description: When the internal timeout for information retrieval expires
      security:
      - BasicAuth: []
      summary: Get stats from a node
      tags:
      - administration
  /raw:
    post:
      consumes:
      - application/json
      description: Sends a raw measurement request to the nodes specified in `sensors`
        and returns a list of `stats.Stats` objects for all sensors taking part in
        the campaign. Will time out in `300ms` if any sensor does not respond.
      parameters:
      - description: Measurement request object
        in: body
        name: id
        required: true
        schema:
          $ref: '#/definitions/types.RawMeasurementRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Bare statistics for all nodes in the measurement campaign.
            Will always include sensor status information.
          headers:
            Location:
              description: Location of the new campaign object.
              type: string
          schema:
            items:
              $ref: '#/definitions/stats.Stats'
            type: array
        "500":
          description: When the internal timeout for information retrieval expires
      security:
      - BasicAuth: []
      summary: Get a raw spectrum measurement from a list of nodes
      tags:
      - measurement
  /samples:
    get:
      description: Returns a list of all the samples recorded during a campaign by
        a specific sensors partaking in said campaign.
      parameters:
      - description: Sensor which the samples belong to
        in: path
        name: sensorId
        required: true
        type: string
      - description: Campaign which the samples belong to
        in: path
        name: campaignId
        required: true
        type: string
      - description: Samples returned will have been received strictly later than
          this date (must be in ISO 8601/RFC 3339)
        in: path
        name: from
        type: string
      - description: Samples returned will have been received strictly before this
          date (must be in ISO 8601/RFC 3339)
        in: path
        name: to
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: All samples which respect the given conditions
          schema:
            items:
              $ref: '#/definitions/models.Sample'
            type: array
        "500":
          description: Generally a database error
      security:
      - BasicAuth: []
      summary: Get samples
      tags:
      - data
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
